@Solomonlol.ShiftLogger_HostAddress = http://localhost:5013

GET {{Solomonlol.ShiftLogger_HostAddress}}/api/employees
Accept: application/json

###
POST {{Solomonlol.ShiftLogger_HostAddress}}/api/employees
Content-Type: application/json
{
  "FirstName": "Bruse",
  "LastName": "Wayne",
  "EmployeeNumber": "4"
}

###
GET {{Solomonlol.ShiftLogger_HostAddress}}/api/employees/1
Accept: application/json

###
DELETE {{Solomonlol.ShiftLogger_HostAddress}}/api/employees/1

###
PUT {{Solomonlol.ShiftLogger_HostAddress}}/api/employees/2
Content-Type: application/json
{
  "FirstName": "Solomon",
  "LastName": "Kane",
  "EmployeeNumber": "4"
}

###
GET {{Solomonlol.ShiftLogger_HostAddress}}/api/shifts
Accept: application/json

###
POST {{Solomonlol.ShiftLogger_HostAddress}}/api/shifts/224
Content-Type: application/json
{
    "startTime": "2026-08-20T14:42:04.4389831",
    "endTime": null,
    "isEnded": false,
    "employeeId": 5,
}